import {StyleSheet, Dimensions, Platform} from 'react-native';
import {getStatusBarHeight} from 'app-common';

const deviceWidth = Dimensions.get('window').width;
const deviceHeight = Dimensions.get('window').height;

const isIos = Platform.OS === 'ios';
export default StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    flex: 1,
    paddingTop: Platform.OS !== 'ios' ? getStatusBarHeight() : 0,
  },
  header: {
    paddingTop: Platform.OS === 'ios' ? getStatusBarHeight() : 0,
    marginTop: 20,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  imgBanner: {
    width: deviceWidth,
    height: (198 / 375) * deviceWidth,
    resizeMode: 'contain',
    position: 'absolute',
    top: -20,
    zIndex: -1,
  },
  iconHome: {
    width: 115,
    height: 30,
    resizeMode: 'contain',
  },
  iconHeader: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    marginLeft: 10,
    marginRight: 6,
  },
  imgBottom: {
    width: deviceWidth,
    height: (440 / 1500) * deviceWidth,
    resizeMode: 'contain',
    position: 'absolute',
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  textBottom: {
    marginTop: 40,
    fontSize: 14,
    color: '#fff',
    fontFamily: 'Sniglet-Regular',
    fontWeight: '400',
  },
  logo: {
    height: (98 / 375) * deviceWidth,
    width: (73 / 375) * deviceWidth,
    resizeMode: 'contain',
    // position: "absolute",
  },
  viewLogo: {
    alignSelf: 'center',
    zIndex: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '400',
    fontFamily: 'Sniglet-Regular',
  },
  containerImg: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  text: {
    fontSize: 15,
    color: '#000',
  },
  textInput: {
    flex: 1,
    color: '#000',
    backgroundColor: '#F3F3F3',
    height: 45,
    borderRadius: 4,
    marginBottom: 16,
    paddingHorizontal: 15,
    fontFamily: 'Poppins',
    fontSize: 14,
  },
  button: {
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 1,
    top: deviceHeight / 2 - 20,
  },
  nextButton: {
    height: (264 / 375) * deviceWidth,
    width: (264 / 375) * deviceWidth,
    resizeMode: 'contain',
  },
  iconBack: {
    height: 22,
    width: 22,
    resizeMode: 'contain',
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
  },
  fullname: {
    fontSize: 16,
    color: '#000',
    lineHeight: 24,
    fontWeight: '500',
    fontFamily: 'Poppins-Medium',
  },
  email: {
    fontSize: 13,
    color: '#929292',
    lineHeight: 19,
    fontFamily: 'Poppins',
  },
  overview: {
    paddingHorizontal: 30,
    paddingVertical: 20,
    borderRadius: 24,
    backgroundColor: '#fff',
    marginTop: 25,
    marginHorizontal: 16,
    // width: deviceWidth - 32,
    // height: isIos ? (260 / 375) * deviceWidth : (260 / 375) * deviceWidth + 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 10,
  },
  overTitle: {
    fontSize: 14,
    color: '#000',
    lineHeight: 21,
    fontFamily: 'Poppins',
  },
  viewItem: {
    flexDirection: 'row',
    marginBottom: 22,
    alignItems: 'center',
  },
  iconItem: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    marginRight: 13,
  },
  txtItem: {
    fontFamily: 'Poppins-Medium',
    fontWeight: '500',
    fontSize: 10,
  },
  line: {
    marginTop: 4,
    width: (150 / 375) * deviceWidth,
    height: 6,
    borderColor: '#000',
    borderWidth: 1,
  },
  progress: {
    height: 4,
  },
  txt1: {
    fontFamily: 'Poppins',
    fontSize: 12,
    lineHeight: 18,
    color: '#929292',
  },
  viewList: {
    // paddingHorizontal: 16,
  },
  titleList: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    lineHeight: 24,
    color: '#000',
    fontWeight: '500',
    marginLeft: 16,
    marginVertical: 25,
  },
  txtAllSource: {
    fontFamily: 'Poppins-ExtraLight',
    fontSize: 13,
    lineHeight: 19,
    color: '#929292',
    fontWeight: '300',
    textDecorationLine: 'underline',
  },
  loginRegister: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  loginRegisterText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
  },
  loginRegisterIcon: {
    color: '#000',
    fontWeight: '500',
    marginHorizontal: 5,
  },
  dot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ef4444',
  },
  topPilotsWrapper: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginTop: 20,
    justifyContent: 'space-between',
  },
  pilotCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 4,
  },
  medal: {fontSize: 18, marginRight: 6},
  pilotName: {flex: 1, fontSize: 14, fontFamily: 'Poppins-Medium', color: '#000', fontWeight: '600'},
  pilotBottomRow: {flexDirection: 'row', alignItems: 'center', marginTop: 6},
  pilotAirports: {flex: 1, fontSize: 12, color: '#555', fontFamily: 'Poppins'},
  rankPill: {paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20},
  rankPillText: {color: '#fff', fontSize: 11, fontFamily: 'Poppins-Medium', fontWeight: '600'},
  podiumSection: {marginTop: 24, paddingHorizontal: 16},
  podiumTitle: {fontFamily: 'Poppins-Medium', fontSize: 16, lineHeight: 24, fontWeight: '600', color: '#000', marginBottom: 12},
  podiumWrapper: {flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between'},
  podiumColumn: {flex: 1, backgroundColor: '#fff', marginHorizontal: 4, borderRadius: 16, alignItems: 'center', paddingTop: 12, paddingBottom: 14, paddingHorizontal: 8, shadowColor: '#000', shadowOffset:{width:0,height:2}, shadowOpacity:0.08, shadowRadius:6, elevation:4},
  podiumFirst: {height: 170},
  podiumSecond: {height: 140, marginTop: 30},
  podiumThird: {height: 125, marginTop: 45},
  podiumMedal: {fontSize: 26, marginBottom: 4},
  podiumName: {fontSize: 12, fontFamily: 'Poppins-Medium', fontWeight: '600', color: '#111', marginBottom: 4, textAlign: 'center', paddingHorizontal: 4},
  podiumAirports: {fontSize: 11, fontFamily: 'Poppins', color: '#555', marginBottom: 6},
  podiumRankLabel: {position: 'absolute', top: 8, right: 8, fontSize: 10, fontFamily: 'Poppins-Medium', color: '#444'},
  topPilotsRow: {flexDirection: 'row', paddingHorizontal: 8, marginTop: 0},
  topPilotsRowTablet: {flexDirection:'row', paddingHorizontal:8, marginTop:18},
  pilotCardInline: {flex:1, backgroundColor:'#fff', borderRadius:18, paddingVertical:8, paddingHorizontal:12, marginHorizontal:4, flexDirection:'row', alignItems:'center', shadowColor:'#000', shadowOffset:{width:0,height:2}, shadowOpacity:0.06, shadowRadius:4, elevation:3},
  pilotInfo: {flexDirection:'row', alignItems:'center', flex:1, marginRight:6},
  medalEmoji: {fontSize:18, marginRight:6},
  pilotTextWrap: {flex:1},
  pilotNameInline: {fontFamily:'Poppins-Medium', fontSize:13, lineHeight:18, color:'#111', fontWeight:'600'},
  pilotAirportsInline: {fontFamily:'Poppins', fontSize:11, lineHeight:16, color:'#777', marginTop:2},
  rankBadge: {borderRadius:999, paddingHorizontal:16, paddingVertical:6, justifyContent:'center', alignItems:'center', minWidth:82},
  rankBadgeText: {fontFamily:'Poppins-Medium', fontSize:11, lineHeight:16, fontWeight:'600', color:'#fff'},
  pilotCardVertical: {flex:1, backgroundColor:'#fff', borderRadius:26, paddingTop:0, paddingBottom:14, marginHorizontal:6, alignItems:'center', shadowColor:'#000', shadowOffset:{width:0,height:2}, shadowOpacity:0.05, shadowRadius:10, elevation:3, overflow:'hidden'},
  medalEmojiLarge: {fontSize:24, marginBottom:4, marginTop:10},
  pilotNameCard: {fontFamily:'Poppins-Medium', fontSize:14, lineHeight:18, fontWeight:'600', color:'#111', marginBottom:2},
  pilotAirportsCard: {fontFamily:'Poppins', fontSize:13, lineHeight:17, color:'#6A6A6A', marginBottom:10},
  rankPillCard: {borderRadius:999, paddingHorizontal:18, paddingVertical:6, minWidth:78, alignItems:'center'},
  medalStack: {alignItems:'center', marginBottom:2, paddingTop:0, marginTop:0, width:'100%'},
  ribbonBar: {position:'absolute', top:0, width:26, height:7, borderTopLeftRadius:0, borderTopRightRadius:0, backgroundColor:'#3173C5'},
});
